# Generated by Django 4.1.6 on 2023-02-21 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Country/region name", max_length=30, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type of tea or offering", max_length=30, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this type of tea"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Business name of the vendor",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL for this vendor's store", unique=True
                    ),
                ),
                (
                    "url_alt",
                    models.URLField(
                        blank=True, help_text="Alternate URL for this vendor's store."
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the vendor"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("established", models.DateField(blank=True, null=True)),
                ("created", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, max_length=250)),
                (
                    "ship_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select locations this vendor ships to",
                        related_name="ship_to",
                        to="tealist.location",
                    ),
                ),
                (
                    "store_location",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select locations this vendor ships from",
                        related_name="store_location",
                        to="tealist.location",
                    ),
                ),
                (
                    "tea_source",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select locations this vendor sources tea from",
                        related_name="tea_source",
                        to="tealist.location",
                    ),
                ),
                (
                    "variety",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select the varieties of tea this vendor sells",
                        to="tealist.variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tealist.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
            },
        ),
    ]
