# Generated by Django 4.1.6 on 2023-02-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
