# Generated by Django 4.1.6 on 2023-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                fields=("vendor", "user"), name="One comment per user per vendor"
            ),
        ),
    ]
