# Generated by Django 4.1.6 on 2023-02-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0003_vendor_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="url",
            field=models.URLField(help_text="URL for this vendor's store"),
        ),
    ]
