# Generated by Django 4.1.6 on 2023-03-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0003_comment_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
