# Generated by Django 4.1.6 on 2023-02-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0004_alter_vendor_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Country/region name", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="variety",
            name="name",
            field=models.CharField(
                help_text="Type of tea or offering", max_length=30, unique=True
            ),
        ),
    ]
