# Generated by Django 4.1.6 on 2023-03-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0004_vendor_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=2, null=True
            ),
        ),
    ]
