# Generated by Django 4.1.6 on 2023-02-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0005_alter_location_name_alter_variety_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="url_alt",
            field=models.URLField(
                blank=True,
                help_text="Alternate URL for this vendor's store.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="url",
            field=models.URLField(help_text="URL for this vendor's store", unique=True),
        ),
    ]
