# Generated by Django 4.1.6 on 2023-02-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0006_vendor_url_alt_alter_vendor_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="url_alt",
            field=models.URLField(
                blank=True, help_text="Alternate URL for this vendor's store."
            ),
        ),
    ]
