# Generated by Django 4.1.6 on 2023-03-19 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tealist", "0006_vendor_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private", models.BooleanField(default=True)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Info about this collection"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendors",
                    models.ManyToManyField(
                        help_text="Which vendors belong to this collection",
                        to="tealist.vendor",
                    ),
                ),
            ],
        ),
    ]
