# Generated by Django 4.1.6 on 2023-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0007_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="name",
            field=models.CharField(
                default="test",
                help_text="What do you want to call this vendor",
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
