# Generated by Django 4.1.6 on 2023-02-14 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0007_alter_vendor_url_alt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="promoted",
        ),
    ]
