# Generated by Django 4.1.6 on 2023-03-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0010_collection_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="f960", editable=False, max_length=6),
        ),
    ]
