# Generated by Django 4.1.6 on 2023-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0011_collection_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="ee61", editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name="collection",
            name="vendors",
            field=models.ManyToManyField(
                help_text="Which vendors belong to this collection",
                related_name="collection_vendors",
                to="tealist.vendor",
            ),
        ),
    ]
