# Generated by Django 4.1.6 on 2023-03-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0013_collection_created_on_alter_collection_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="8f93", editable=False, max_length=6),
        ),
    ]
