# Generated by Django 4.1.6 on 2023-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0015_alter_collection_unique_id_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="5805", editable=False, max_length=6),
        ),
    ]
