# Generated by Django 4.1.6 on 2024-01-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0017_alter_collection_unique_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name_plural": "Locations"},
        ),
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="e8a8", editable=False, max_length=6),
        ),
    ]
