# Generated by Django 4.2.9 on 2024-01-03 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tealist", "0022_alter_collection_unique_id_alter_rating_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name_plural": "Ratings"},
        ),
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="e50d", editable=False, max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("vendor", "user")},
        ),
    ]
