# Generated by Django 4.2.9 on 2024-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0023_alter_rating_options_alter_collection_unique_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="8c0c", editable=False, max_length=6),
        ),
    ]
