# Generated by Django 4.2.9 on 2024-01-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0026_alter_collection_unique_id_alter_rating_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="b63e", editable=False, max_length=6),
        ),
    ]
