# Generated by Django 4.2.9 on 2024-01-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0027_alter_collection_slug_alter_collection_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=126)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateField(blank=True, null=True)),
                ("handle", models.CharField(max_length=256)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tealist.vendor"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="af4c", editable=False, max_length=6),
        ),
        migrations.CreateModel(
            name="TeaVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=126)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "tea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tealist.tea"
                    ),
                ),
            ],
        ),
    ]
