# Generated by Django 4.2.9 on 2024-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0034_tea_variety_teavariant_compare_at_price_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="d6ec", editable=False, max_length=6),
        ),
    ]
