# Generated by Django 4.2.9 on 2024-02-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0036_alter_collection_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="a400", editable=False, max_length=6),
        ),
    ]
