# Generated by Django 4.2.9 on 2024-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0037_alter_collection_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tea",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="710e", editable=False, max_length=6),
        ),
    ]
