# Generated by Django 4.2.9 on 2024-02-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tealist", "0038_tea_on_sale_alter_collection_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="unique_id",
            field=models.CharField(default="3898", editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name="tea",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tea_vendor",
                to="tealist.vendor",
            ),
        ),
    ]
