---
name: Dokku Deploy - Dev

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@23.239.17.96:22/~/teahookup' # https://github.com/dokku/github-action/issues/15
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
