name: Fly Deploy - Prod
on:
  workflow_run:
    workflows: [Dokku Deploy - Dev]
    types:
      - completed


jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

